### ISSUE TITLE
jupyter not persistant storage

### ISSUE THREAD

**Issue by seblinux-enod** [cetic/fadi#119]
When I restart minikube, i lose all my work in jupyter. 
It is a bug in the installation or it is a feature to configure ?

local installation of FADI in centos 8, minikube and kubernetes 1.15

 Br

**Comment by alexnuttinck** [comment]
Resolved by the new [helm-fadi release: 0.2.4](https://github.com/cetic/helm-fadi/releases/tag/0.2.4).
I close this issue.
