### ISSUE TITLE
Tsaas server installed with FADI not found 

### ISSUE THREAD

**Issue by fzalila** [cetic/fadi#121]
**Describe the bug**
Create a **Stream** with tsaas and swagger-ui fails.

**Environment**:
Provide the environment in which the bug has happened (minikube on a workstation, full fledged Kubernetes cluster, ...)

* **OS** Mac OS 10.15.3
* **VM driver** virtualbox
* **Minikube version** 1.6.2

**What happened**:
Launching tsaas and swagger-ui with FADI creates a server named  http://api-tsimulus.fadi.minikube. This server is not found when I try to create a stream.

**What you expected to happen**:
Start streaming

**How to reproduce it** (as minimally and precisely as possible):

- Install FADI with **only** tsaas and swagger-ui enabled (true).
- Post a stream
- start the stream

**Output of `minikube logs` (if applicable)**:
TypeError: Aucun serveur ayant le nom d’hôte précisé n’a pu être trouvé.

**Anything else we need to know**:
When I do the same process with tsaas user guide [here](https://github.com/cetic/tsimulus-saas) everything works perfectly.

**Comment by alexnuttinck** [comment]
You need to enable the ingress plugin and to add this URL in your /etc/hosts with the minikube ip if you want this to work. 
But default values from the helm-fadi chart should be updated as we do not setup ingress configs by default.
