### ISSUE TITLE
Deadline deprecated stable / incubator repos.

### ISSUE THREAD

**Issue by alexnuttinck** [cetic/fadi#124]
**Is your feature request related to a problem? Please describe.**
 
Incubator & Stable repos from Helm will be soon deprecated.
See https://github.com/helm/charts#deprecation-timeline for the details.

**Describe the solution you'd like**

* Update Fadi dependencies in helm-fadi repo.
* Update the install doc accordingly.

**Comment by banzo** [comment]
@alexnuttinck I think this is done now, right?

**Comment by alexnuttinck** [comment]
Yes it's done, I close this issue.
