### ISSUE TITLE
PVC randomly stuck in state Pending

### ISSUE THREAD

**Issue by alexnuttinck** [cetic/fadi#128]
**Describe the bug**

When I install fadi in minikube, some pvc are stuck in pending state, and these containers are not created.

**Environment**:

Minikube:
```
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd
```

Kubectl:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know**:

Seems to be related to the version of minikube, and the storage-provisioner plugin.
Issues related to our problem:
* https://github.com/kubernetes/minikube/issues/7828
* https://github.com/kubernetes/minikube/issues/6523

Error from storage-provisioner pod:

```
k8s.io/minikube/vendor/github.com/r2d4/external-storage/lib/controller/controller.go:411: Failed to list *v1.PersistentVolumeClaim: v1.PersistentVolumeClaimList: Items: []v1.PersistentVol
```

**Comment by banzo** [comment]
I can not reproduce the problem with recent versions of minikube, closing this.
