### ISSUE TITLE
FADI Chart maintainers

### ISSUE THREAD

**Issue by alexnuttinck** [cetic/fadi#132]
**Is your feature request related to a problem? Please describe.**
We need to check if every chart used by FADI has a maintainer, as I will soon be leaving the Cetic.

**Describe the solution you'd like**
We need at least one maintainer per chart.

Current maintainers:

helm-fadi: @alexnuttinck / @banzo / @AyadiAmen 
helm-zabbix: @alexnuttinck / @AyadiAmen /@aeciopires (external)
helm-swagger-ui: @Sellto  / @alexnuttinck
helm-nifi:  @alexnuttinck, who else?
helm-drupal: no maintainer, @AyadiAmen?
helm-microservice: @terence-bigtt, @alexnuttinck
helm-postgresql: @alexnuttinck, @AyadiAmen
helm-adminer: @alexnuttinck, who else?
helm-phpLDAPadmin: @alexnuttinck / @AyadiAmen
helm-tsimulus-saas: @AyadiAmen / @alexnuttinck
helm-mlflow: no maintainer, @Sellto?

Who wants to be a chart maintainer ? :smile:

**Comment by fzalila** [comment]
@alexnuttinck 
I can start by maintaining helm-adminer chart.

**Comment by aeciopires** [comment]
Hi @alexnuttinck! 

I will continue to keep the helm-zabbix chart.

**Comment by alexnuttinck** [comment]
Hey @aeciopires, thank you very much! And thanks for your really good work on the helm-zabbix chart. :smile:. 

@fzalila you are now a chart maintainer, congratulations :fireworks: !

**Comment by AyadiAmen** [comment]
Hello @alexnuttinck,

I can maintain the nifi and Drupal ( obviously ) helm harts, I can also be a maintainer for the adminer chart alongside Faiez.

**Comment by alexnuttinck** [comment]
Ok, thanks @AyadiAmen. 

Also, @Sellto will have no time to maintain these chart as he doesn't work on FADI anymore. 
So I propose, if you agree @AyadiAmen, that you maintain the swagger-ui chart instead of the adminer chart. It's quite the same, as it's only a UI.

**Comment by SellamiRami** [comment]
Hello, @alexnuttinck, I can maintain the Swagger-ui Helm Chart. Added to that, you can consider me for Adminer whether you need two maintainers.

**Comment by alexnuttinck** [comment]
Ok perfect @SellamiRami, Thanks!

It remains the mlflow chart, is it still used in FADI?

If yes, who maintains this chart?
If no, do we deprecate the chart?

**Comment by alexnuttinck** [comment]
All, I gave you the admin/maintain rights on the different Helm chart repositories.

**Comment by alexnuttinck** [comment]
We have decided to not deprecate the mlflow chart for the moment. I close this issue, thank you all!
