### ISSUE TITLE
Grafana is readonly

### ISSUE THREAD

**Issue by banzo** [cetic/fadi#20]
**Describe the bug**: In a GCP kubernetes deployment of FADI, Grafana is readonly (cannot create dashboards, playlist, ...)
**Version of Helm and Kubernetes**: latest on GCP
**Which chart**: Grafana
**What happened**: log in as `admin`/`password1`, dashboard creation UI elements are missing
**What you expected to happen**: the dashboard creation UI elements to be present (along with the other admin features for the `admin` user)
**How to reproduce it**: go to the bd@MA testbed (probably it can also be reproduced in the minikube dev env)

**Comment by AyadiAmen** [comment]
@banzo 
The bug has been fixed, can you review the last pull request ? thank you in advance

**Comment by banzo** [comment]
Works fine on my local minikube now, thanks
