### ISSUE TITLE
Nifi template is not complete in the USERGUIDE

### ISSUE THREAD

**Issue by fzalila** [cetic/fadi#25]
**What happened**:
When experimenting the [USERGUIDE.md](../blob/master/USERGUIDE.md), the provided [nifi_template](../blob/master/examples/basic/nifi_template.xml) does not correspond to the provided [screenshot](../blob/master/examples/basic/images/nifi_csv_to_sql.png). In fact the `PutDatabaseRecord` process does not exit in the template.

**What you expected to happen**:
Load a compte Nifi template. 

**How to reproduce it** (as minimally and precisely as possible):
Just experiment the [USERGUIDE.md](../blob/master/USERGUIDE.md).

**Anything else we need to know**:
I will fix it.

**Comment by banzo** [comment]
WIP in https://github.com/cetic/fadi/tree/user-guide-feature
