### ISSUE TITLE
Failed to fetch Grafana Dashboard

### ISSUE THREAD

**Issue by fzalila** [cetic/fadi#26]
**What happened**:
I experiment the [USERGUIDE](../blob/master/USERGUIDE.md). In section [3. Display dashboards and configure alerts](../blob/master/USERGUIDE.md#3-display-dashboards-and-configure-alerts), I start by logging in Grafana. However, immediately after I logged in, an error message is shown **Failed to fetch dashboard Unauthorized**.
More details in this [video](../blob/user-guide-feature/doc/videos/Grafana.mov).

**What you expected to happen**:
Obtain the Grafana Dashboard.

**Comment by AyadiAmen** [comment]
it's fixed

**Comment by banzo** [comment]
Great, can you please give details on the how it was fixed/what the issue was?

Then we can close this issue.

**Comment by banzo** [comment]
It works with the ip, but not with the `/etc/hosts` url.

Maybe we can fix that in the grafana config file (options `domain` and `root_url`?) or abandon the minikube host file trick.

**Comment by banzo** [comment]
We do not use /etc/hosts on local minikube anymore

**Comment by vvxxvvxx** [comment]
Hi @banzo , I met the same issue. How did fix that finally?

**Comment by banzo** [comment]
We are not using minikube in that way anymore.
