### ISSUE TITLE
Add contributors section

### ISSUE THREAD

**Issue by alexnuttinck** [cetic/fadi#27]
Add a contributors section in the Readme.md.

I have enabled the https://github.com/all-contributors/all-contributors bot for this repo.

**Comment by alexnuttinck** [comment]
Let's have a try!

@all-contributors add @banzo for code and review.

**Comment by alexnuttinck** [comment]
@all-contributors add @alexnuttinck for code, review and infra.

**Comment by alexnuttinck** [comment]
@all-contributors add @AyadiAmen for code :)

**Comment by alexnuttinck** [comment]
@all-contributors add @fzalila for code and tests.

**Comment by alexnuttinck** [comment]
@all-contributors add @alexnuttinck for code, review and infra.

**Comment by alexnuttinck** [comment]
@all-contributors add @alexnuttinck for code, review and infra.

**Comment by alexnuttinck** [comment]
Need to restart the process due to some merge conflicts..

@all-contributors add @AyadiAmen for code.

**Comment by alexnuttinck** [comment]
@all-contributors add @fzalila for code and tests.

**Comment by alexnuttinck** [comment]
Ok, I close this issue.

**Comment by banzo** [comment]
@all-contributors add @AyadiAmen for design.

**Comment by banzo** [comment]
@all-contributors add @FabianSteels  for ideas. 

(until there is a role for the technical specs)

**Comment by banzo** [comment]
@all-contributors add @smouton-cetic  for projectManagement.

**Comment by banzo** [comment]
@all-contributors add @nikosmtsk  for projectManagement.

**Comment by banzo** [comment]
@all-contributors add @Sellto  for doc.

**Comment by banzo** [comment]
@all-contributors add @terence-bigtt for code.

**Comment by alexnuttinck** [comment]
@all-contributors add @Maher-badri for projectManagement.

**Comment by banzo** [comment]
@all-contributors add @mgoeminne for ideas.

**Comment by banzo** [comment]
@all-contributors add @SellamiRami for review
