### ISSUE TITLE
Postgresql secrets not found

### ISSUE THREAD

**Issue by fzalila** [cetic/fadi#45]
**What happened**:

When I try to do the user guide, the command `export POSTGRES_PASSWORD=$(kubectl get secret --namespace fadi fadi-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)` returns this error `Error from server (NotFound): secrets "fadi-postgresql" not found`.

Any idea how to resolve this issue?

**Comment by AyadiAmen** [comment]
hi,
you don't need that command anymore, the default username and password for postgres are admin - password1 ( the user from the ldap server )

**Comment by fzalila** [comment]
Thanks @AyadiAmen. It works perfectly.
