### ISSUE TITLE
PGAdmin is not available on GCP

### ISSUE THREAD

**Issue by banzo** [cetic/fadi#5]
Web interface works fine in minikube but not on GCP.

Maybe something to do with ssl config?

**Comment by alexnuttinck** [comment]
We need to make a test with the modifications made in this PR: https://github.com/cetic/helm-pgadmin/pull/11

**Comment by alexnuttinck** [comment]
SSL seems to not resolve the problem after a test made on GKE.
There is a `404 page not found` when I am redirected on /login?next=%2F.

**Comment by banzo** [comment]
see #89
