### ISSUE TITLE
More easier install of fadi stack

### ISSUE THREAD

**Issue by fzalila** [cetic/fadi#59]
The following bloc allows to install and configure the fadi cluster.

```bash
kubectl config set-context minikube
minikube addons enable ingress
cd helm
# you can edit values.yaml file to customise the stack
./deploy.sh
# see deploy.log for connection information to the various services
# specify the fadi namespace to see the different pods
kubectl config set-context minikube --namespace fadi
```

To make the install of fadi more easier, is it possible to integrate the different commands (kubectl config...) inside the deploy.sh script?

**Comment by alexnuttinck** [comment]
@fzalila These commands:

```
kubectl config set-context minikube
minikube addons enable ingress
```

are related to `minikube`. 

If you add these commands to the `deploy.sh` file, you won't be able to use it in other contexts than minikube.

**Comment by fzalila** [comment]
Thanks @alexnuttinck !
