### ISSUE TITLE
Launch Jupyter

### ISSUE THREAD

**Issue by fzalila** [cetic/fadi#60]
When we launch the Jupyter service using ```bash minikube service -n fadi proxy-public```, two tabs with two ip adresses are created in the browser: one is responsive and the second one is non-responsive.

Is it correct as behavior?

**Comment by fzalila** [comment]
In addition, when we do in the Terminal ```minikube service -n fadi proxy-public```, the table shows two URLs.
It is expected to obtain 1 or 2 URLs.

Best,

Faiez

**Comment by alexnuttinck** [comment]
Yes, it is the excepted behaviour. The jupyterhub helm chart is designed like that. Rename the service name should be great, but the option is not proposed by the chart. See https://github.com/jupyterhub/zero-to-jupyterhub-k8s for more infos.
