### ISSUE TITLE
Cron job is it the appropriate solution

### ISSUE THREAD

**Issue by fzalila** [cetic/fadi#63]
To deal with the multiple pg-ldap-sync pods created simultaneously, an alternative solution is to change the cron job for example to 20 minutes. Good solution! 

However, imagine that the last cron was triggered at a given time ```t```.

Just after, at ```x+ε``` time, a new user is created in the openldap service.
So, he/she will need to wait around 20 minutes to be able to access to the postgresql service.

Does exit an alternative to the cron job to deal with kind of situation (a listener for example).

Best, 
FZ.

**Comment by alexnuttinck** [comment]
For me, I suggest to let the default behaviour: the pg-ldap-sync is triggered every 1 minute.

At this time, I don't find a better alternative. If you have suggestions, do not hesitate.

**Comment by alexnuttinck** [comment]
I close this issue, if there are suggestions, do not hesitate to reopen this issue.
