### ISSUE TITLE
Service enabling override is not taken into account

### ISSUE THREAD

**Issue by banzo** [cetic/fadi#71]
**Describe the bug**

Modifications to the `values.yml` file in this repo are not taken into account

**Environment**:

* latest Arch and OSX
* latest Minikube
* latest kvm/Virtualbox

**What happened**:

Tired to disable unused services (`enabled:false`) such as Spark, but the whole Spark cluster was still started by `deploy.sh`.

**What you expected to happen**:

disabled services in this repo's config file should not be started, overriding the default helm-fadi config

**How to reproduce it** (as minimally and precisely as possible):

disable e.g. Spark in this repo's `values.yml`, start a fresh minikube and deploy

**Comment by alexnuttinck** [comment]
Hello @banzo, 

Do you still have this problem?

I can't reproduce your bug on my environment. (fedora 30, minikube 1.0.0, virtualbox 6.0).

Be careful to add a space when you disable, enable component of fadi.

* won't work: `enabled:false`
* will work: `enable: false`

**Comment by banzo** [comment]
> Be careful to add a space when you disable, enable component of fadi.

That was the issue, thanks
