### ISSUE TITLE
Remove traefik from install script

### ISSUE THREAD

**Issue by banzo** [cetic/fadi#72]
traefik is not used in minikube, move that part in the standalone/cloud K8S cluster install doc

**Comment by alexnuttinck** [comment]
+ add Documentation on how to use a Ingress Controller like Traefik with Fadi. It should be coupled with the ssl doc.

**Comment by alexnuttinck** [comment]
#85 describes how to setup Traefik

I need to remove the traefik part from the install.sh script.

**Comment by alexnuttinck** [comment]
Done in https://github.com/cetic/fadi/commit/de3c4f380a017a37992817e10c759bf810045064.
