### ISSUE TITLE
Add message broker component

### ISSUE THREAD

**Issue by banzo** [cetic/fadi#76]
**Is your feature request related to a problem? Please describe.**

The toolbox needs tools to facilitate streaming ingestion and processing.
This is currently handled by Apache Nifi, a more complete message queuing solution is needed.

**Describe the solution you'd like**

Add the Kafka message broker to the stack, document setup and usage instructions.

**Describe alternatives you've considered**

Apache Pulsar was considered but is currently on hold - WIP here: 
https://github.com/cetic/helm-fadi/tree/feature/pulsar

**Additional context**

* Kafka can be leveraged to add MQTT support down the line (#54)

**Comment by banzo** [comment]
https://github.com/cetic/helm-fadi/pull/14

**Comment by alexnuttinck** [comment]
@Sellto  @banzo Can we close this issue?

**Comment by banzo** [comment]
see https://github.com/cetic/fadi/tree/master/examples/kafka
