### ISSUE TITLE
Management of application logs

### ISSUE THREAD

**Issue by banzo** [cetic/fadi#77]
**Is your feature request related to a problem? Please describe.**

Easily monitor and consult the application logs (errors, warnings, debug), to audit / trace the actions of the users a posteriori (for example in case of audit). 
The goal is to set up a tool for log management to centralize logs of the FADI components and other system components. 

**Describe the solution you'd like**

* add Elastic-stack to the toolbox: ElasticSearch, Logstash, Kibana, ...
* installation and usage documentation

**Describe alternatives you've considered**

Apache Solr

**Comment by banzo** [comment]
Needs LDAP integration before we can close this.

**Comment by alexnuttinck** [comment]
@AyadiAmen @banzo Can we close this issue?

**Comment by AyadiAmen** [comment]
@alexnuttinck The ldap integration is done but it's not documented yet, so we will close it when the documentation is finished

**Comment by AyadiAmen** [comment]
Once this PR https://github.com/cetic/fadi/pull/103 is approved, you can close this issue
