### ISSUE TITLE
None service accessible after a FADI installation on a generic kubernetes cluster

### ISSUE THREAD

**Issue by sroussea** [cetic/fadi#81]
Hello,

First, we have tried to install the Fadi Framework on a generic kubernetes cluster from scratch by following the installation procedure.
[https://github.com/cetic/fadi/blob/master/INSTALL.md]
We were face to an issue due to the default storageClass that were not automaticaly configure during the installation.
Amen, a guy from the cetic, had taken the hand remotely and fix the issue, thanks to him
[https://github.com/cetic/helm-fadi/issues/15]

Now, FADI seems to be installed, I mean all the pods are running but now we are not able to access to any application of the FADI Framework from any http request. (Pgadmin, nifi, postgress, grafana, ...)

We are just trying to follow the step 2 of the sample case userguide
[https://github.com/cetic/fadi/blob/master/USERGUIDE.md]

The Minikube command "minikube service -n fadi fadi-pgadmin" is dedicated to a FADI installed on a minikube VM but we are here on a generic kubernetes cluster and the procedure does not indicate how to access to a Fadi Framework installed on a generic kubernetes cluster like the ours.

We have checked the settings by two commands :
kubectl cluster-info
kubectl get services

According these settings, we have tried for example to access to the pgadmin entrypoint :
https://192.168.1.30:30374 or http://192.168.1.30:30374
We have also tried by using the kubedns rest api but without success. 

Could you help us on that because we have not yet received any answer to our last email, the 24 october ?

Best regards

![no services](https://user-images.githubusercontent.com/57133449/67755846-2efe2c00-fa39-11e9-9fa2-13087c34910f.png)

Stéphane Rousseau
Safran Aero Boosters

**Comment by AyadiAmen** [comment]
i tried to access the services by forwarding their ports and I got access to pgadmin, grafana, superset, jupyterhub and phpLDAPadmin but there was an error with nifi.
 
to **forward** a port:

```bash
kubectl port-forward <pod-name> <locahost-port>:<pod-port>
```

to get the **\<pod-port>** (the port in which runs the service):

```
kubectl get pods <pod-name> --template='{{(index (index .spec.containers 0).ports 0).containerPort}}{{"\n"}}'
```

after forwarding the port you can open your browser you go to localhost:\<localhost-port> .

with Nifi I got this error:

```
Handling connection for 8080
E1030 15:53:32.887812 6904 portforward.go:400] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 
dfb8617eeb4e8b300cb580af4e924b423d0e36d625405a575eac8d33b4264064, uid : exit status 1: 2019/10/30 15:53:32 socat7426 E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
```

**Comment by alexnuttinck** [comment]
@AyadiAmen it is the `fadi-nifi` service you need to forward, not the `fadi-nifi-headless`.

**Comment by AyadiAmen** [comment]
@alexnuttinck I used the pod-name `fadi-nifi-0` to forward the port for the service `fadi-nifi` .

**Comment by alexnuttinck** [comment]
@AyadiAmen, could you try to port-forward from the svc?
https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/#forward-a-local-port-to-a-port-on-the-pod

**Comment by alexnuttinck** [comment]
the service `fadi-nifi` is on port 80, not 8080.

**Comment by AyadiAmen** [comment]
I tried with this: 

```
kubectl port-forward svc/fadi-nifi 80:80
```

and I still get the same error.

**Comment by AyadiAmen** [comment]
Since nifi is a NodePort service you can access it by requesting \<NodeIP>:\<NodePort>
I tested this with nifi and all the other services of type NodePort and they all work, i had access to Nifi, Grafana, Superset, phpLDAPadmin, pgadmin and Minio with the method mentioned above, and JupyterHub by forwarding the port since it's of type ClusterIP. 

You have all the mentioned services running on your firefox browser.

Does this solve the issue ?

**Comment by FabianSteels** [comment]
it seems that Nifi (v1.12.1) has a issue to forward ports. The only solution I found is to use traefik to reach Nifi. To use traefic, you need an IP. On local you have to use `minikube tunnel` and set up your /etc/hosts file, on premise a IP must be configured probably with MetalLB.
