### ISSUE TITLE
Postgresql databases not persistent

### ISSUE THREAD

**Issue by thierrypirnay** [cetic/fadi#82]
**Describe the bug**
When stopping and restarting Minikube, all the Databases and tables created with pgAdmin disappears.

**Environment**:

* **OS** Microsoft Windows 10 Pro 10.0.17763 Build 17763
* **VM driver** Virtualbox
* **Minikube version** v1.5.2
* **Kubernetes version** v1.15.4

**What happened**:
When stopping then restarting Minikube, all the Databases and Tables created with pgAdmin disappears.
Only the Server created is still present.

**What you expected to happen**:
When restarting Minikube, the tables and databases created are still present

**How to reproduce it** (as minimally and precisely as possible):

1. Start Minikube
2. Deploy fadi
3. Add a server connected to fadi-postgresql
4. Add databases and tables with pgAdmin
4. Stop Minikube
5. Start Minikube

**Output of `minikube logs` (if applicable)**:
[MinikubeLogs_191120.TXT](https://github.com/cetic/fadi/files/3869118/MinikubeLogs_191120.TXT)

**Comment by mgoeminne** [comment]
As discussed by e-mail, @AyadiAmen proposed a solution consisting in mounting hostPath persistent volumes.

https://serverfault.com/questions/979901/minikube-files-do-not-persist-after-restart/979957

https://minikube.sigs.k8s.io/docs/reference/persistent_volumes/

Internal bug ticket #26399

**Comment by alexnuttinck** [comment]
@thierrypirnay @mgoeminne 
Persitence of postgresql helm chart is now corrected in [v0.2.2](https://github.com/cetic/helm-fadi/releases/tag/0.2.2).

I close this issue.
