### ISSUE TITLE
Make the doc and the bash script compatible with helm v3

### ISSUE THREAD

**Issue by alexnuttinck** [cetic/fadi#84]

**Comment by AyadiAmen** [comment]
for now all the services in FADI work with helm 3 except for **minio**, **Kafka**, **logstash**, **filebeat** and **tsaas**. if any of the mentioned services is enabled you will get this error:

```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"
```

if all the mentioned services are not enabled FADI can run with no problem using the following commands:

 **to install:**
```
helm install fadi cetic/fadi -f values.yaml
```
**to delete:**
```
helm delete fadi 
```
**to upgrade:**
```
helm upgrade fadi cetic/fadi -f values.yaml --reset-values
```
**PS: the service open-ldap crashes when upgrading giving the error:**

```
Error: UPGRADE FAILED: cannot patch "fadi-openldap" with kind Service: Service "fadi-openldap" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```
👉 if you don't need any of the mentioned services, you can use fadi with helm 3.

**workaround for upgrading:**  to upgrade you can change openldap to false, upgrade then change it back to true and upgrade again.

**Comment by alexnuttinck** [comment]
@AyadiAmen @fzalila We need to upgrade the Chart versions that we use in FADI (requirments.yaml in helm-fadi) -> for instance, we are now to the 5.* release of minio which correct the error for helm 3.

**Comment by alexnuttinck** [comment]
Same for tsaas, -> the API of the statefulset must be "apps/v1" and not "apps/v1beta2".

**Comment by alexnuttinck** [comment]
@AyadiAmen has corrected bugs related to helm v3 in this PR https://github.com/cetic/helm-fadi/pull/22

**Comment by alexnuttinck** [comment]
Done, merged in master.

**Comment by alexnuttinck** [comment]
I face the issue explained by @AyadiAmen today, so I reopen this issue. I face another with grafana also after an upgrade with helm.

**Comment by alexnuttinck** [comment]
Ok, it was due to the update from helm v2 to v3. 
See https://github.com/helm/charts/pull/17806#issuecomment-589699143
