### ISSUE TITLE
Provide a web database client for multiple database engines

### ISSUE THREAD

**Issue by banzo** [cetic/fadi#89]
We currently rely on PGAdmin, but may want to use something else than postgresql as the datalake/warehouse.

e.g. https://www.adminer.org/ supports MySQL, MariaDB, PostgreSQL, SQLite, MS SQL, Oracle, SimpleDB, Elasticsearch, MongoDB

**Comment by alexnuttinck** [comment]
Addded in [v0.1.17](https://github.com/cetic/helm-fadi/releases/tag/0.1.17).

**Comment by banzo** [comment]
neat!

Now we need to update the doc (install, userguide, slides) to deprecate pgadmin

**Comment by alexnuttinck** [comment]
@banzo I created a new issue for that.

**Comment by alexnuttinck** [comment]
See #92
