### ISSUE TITLE
Add Documentation about Adminer, and deprecate pgAdmin

### ISSUE THREAD

**Issue by alexnuttinck** [cetic/fadi#92]
**Is your feature request related to a problem? Please describe.**

Adminer has been added to the FADI stack (See Issue #89). (https://www.adminer.org/ supports MySQL, MariaDB, PostgreSQL, SQLite, MS SQL, Oracle, SimpleDB, Elasticsearch, MongoDB)
Now we need to update the doc (install, userguide, slides) to deprecate pgadmin.

#### Checklist

- [x] Update the install script (update helm-fadi), and the documentation related to.
- [x] Update the userguide.
- [x] Update the different slides and presentations. (https://fadi.presentations.cetic.be , ...).
- [x] Update the install script, and the documentation related to.

**Comment by alexnuttinck** [comment]
pgadmin is now removed from helm-fadi (chart 0.1.19).

**Comment by alexnuttinck** [comment]
[pgadmin repo](https://github.com/cetic/helm-pgadmin/) is now archived.

**Comment by alexnuttinck** [comment]
I made a PR #97 where I updated the userguide.

**Comment by banzo** [comment]
@fzalila do the test/use cases need to be adapted accordingly?

**Comment by fzalila** [comment]
@banzo 
For test cases [here](https://github.com/cetic/fadi/blob/feature/testsDOC/tests/doc/Cockburns-specification.md), some test cases should be updated (TC-5, TC-6, TC-7 and TC-8). 
For implemented tests, the pgadmin test is not so advanced. So removing it and replacing it with Adminer tests should be easy to do.

**Comment by alexnuttinck** [comment]
Ok. I think we can close this issue now.
