### ISSUE TITLE
FADI seems not to be deployable on a Kubernetes > 1.16

### ISSUE THREAD

**Issue by alexnuttinck** [cetic/fadi#96]
We need to check that FADI is deployable on Kubernetes with a version more than 1.16.

And correct the charts impacted by that.

**Comment by alexnuttinck** [comment]
@fzalila maybe can you make a test when you resolve issue #84 ?

**Comment by alexnuttinck** [comment]
@AyadiAmen has made a test with kubernetes 1.17 on minikube and it works fine. This PR cetic/helm-fadi#22 corrects some issues. (APIs version, ...)

**Comment by fzalila** [comment]
@alexnuttinck @AyadiAmen @banzo 
I deployed FADI (`master` branch) with minikube using the following versions and different services work perfectly 👌🏼. 

Minikube:
`minikube version: v1.6.2
commit: 54f28ac5d3a815d1196cd5d57d707439ee4bb392`

Helm:
`Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}`

Kubernetes:
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}`

`Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}`

Only `traefik-dashboard` seems to be unstable. The dashboard does not show the different services.

**Comment by alexnuttinck** [comment]
@fzalila ok, great. I think we can close this issue now.

Thank you all.

**Comment by Sellto** [comment]
JupyterHub Chart not compatible with K8S 1.16 and 1.17 (issue https://github.com/cetic/fadi/issues/98)
This issue is reproductible in minikube...

**Comment by alexnuttinck** [comment]
Resolved by the new [helm-fadi release: 0.2.4](https://github.com/cetic/helm-fadi/releases/tag/0.2.4).
I close this issue.
